name: Build and Deploy to Cloud Run

on:
  push:
    branches:
    - main

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  RUN_REGION: us-central1
  SERVICE_NAME: helloworld-python

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.RUN_SA_KEY }}
        project_id: ${{ secrets.RUN_PROJECT }}

    # Build and push image to Google Container Registry
    - name: Build
      run: |-
        gcloud builds submit \
          --quiet \
          --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"
    
    # call istudio api
    - name: infra call
      uses: satak/webrequest-action@master
      with:
        url: http://35.205.77.100:5000/InfraCommand/acemicro@hcl.com/GCP/IkeaTrial/usecase1/install-infra
        method: POST
        payload: '{"flowId": "${{secrets.IS_FLOWID}}", "Client_Email":"${{secrets.IS_CLIENT_EMAIL}}", "GCE_Project_Id":"${{secrets.IS_GCE_PROJECT_ID}}","GCE_Client_Id":"${{secrets.IS_GCE_CLIENT_ID}}", "GCE_Private_Key_Id":"${{secrets.IS_GCE_PRIVATE_KEY_ID}}", "GCE_Private_Key" : "${{secrets.IS_GCE_PRIVATE_KEY}}","Client_Certificate_URL":"${{secrets.IS_CLIENT_CERTIFICATE_URL}}"}'
    
    # Setup terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    
    # Terraform script checkout
    - name: Terraform repository checkout 
      uses: actions/checkout@v2
      with:
        repository: prasadjblin/tf-store
        path: istudio-tf-scripts        
        ssh-strict: false
        #ssh-key: ${{ secrets.MGMT_SSH }}
    
    - name: Terraform init
      id: init
      run: terraform init
      continue-on-error: false
      working-directory: ./istudio-tf-scripts
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      
    - name: Terraform Refresh
      id: refresh
      run: terraform refresh
      continue-on-error: false
      working-directory: ./istudio-tf-scripts
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
    
    - name: Terraform Plan
      id: plan
      run: terraform plan
      continue-on-error: false
      working-directory: ./istudio-tf-scripts
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
    
    # Deploy image to Cloud Run
    - name: Deploy
      run: |-
        gcloud run deploy "$SERVICE_NAME" \
          --quiet \
          --region "$RUN_REGION" \
          --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
          --platform "managed" \
          --allow-unauthenticated
    
    #check service availability       
    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v1.2
      with:
        # Check the following URLs one by one sequentially
        url: https://helloworld-python-5pwvjfrcgq-uc.a.run.app
        follow-redirect: no # Optional, defaults to "no"
        max-attempts: 3 # Optional, defaults to 1
        retry-delay: 5s # Optional, only applicable to max-attempts > 1
