name: Build and Deploy to Cloud Run

on:
  push:
    branches:
    - main

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  RUN_REGION: us-central1
  SERVICE_NAME: helloworld-python
  GCP_PROJECT_ID_PREFIX: 'actiontest'

jobs:
  setup-build-deploy:
    name: "Setup, Build, and Deploy - '${{github.ref}}'"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setting GCP Reference
      run: echo "GCP_REF=${GITHUB_REF##*/}" >> $GITHUB_ENV
    
    - name: Setting GCP Project ID
      run: echo "GCP_PROJECT_ID=${{ env.GCP_PROJECT_ID_PREFIX }}-${{ env.GCP_REF }}" >> $GITHUB_ENV
    
    - name: Setting GCP Service Account secret name
      run: echo "GCP_SERVICE_ACCOUNT_NAME=GCP_SERVICE_ACCOUNT_${{ env.GCP_REF }}" >> $GITHUB_ENV
    
    # Setup gcloud CLI 
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.RUN_SA_KEY }}
        project_id: ${{ secrets.RUN_PROJECT }}

    # Build and push image to Google Container Registry
    - name: Build
      run: |-
        gcloud builds submit \
          --quiet \
          --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:latest"
    
    # Build and push image to Google Container Registry  
    - name: iStudio provisioning
      continue-on-error: false
      run: |-
        curl -X POST http://istudio.thecloudbridge.net:5000/InfraCommand/acemicro@hcl.com/GCP/IkeaTrial/usecase2/install-infra \
             -d 'Client_Email=${{secrets.IS_CLIENT_EMAIL}}' \
             -d 'GCE_Project_Id=${{secrets.IS_GCE_PROJECT_ID}}' \
             -d 'GCE_Client_Id=${{secrets.IS_GCE_CLIENT_ID}}' \
             -d 'GCE_Private_Key_Id=${{secrets.IS_GCE_PRIVATE_KEY_ID}}' \
             -d 'GCE_Private_Key=${{secrets.IS_GCE_PRIVATE_KEY}}' \
             -d 'Client_Certificate_URL=${{secrets.IS_CLIENT_CERTIFICATE_URL}}'      
     
    #check service availability       
    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v1.2
      with:
        # Check the following URLs one by one sequentially
        url: https://hello-python-5pwvjfrcgq-uc.a.run.app
        follow-redirect: no # Optional, defaults to "no"
        max-attempts: 3 # Optional, defaults to 1
        retry-delay: 5s # Optional, only applicable to max-attempts > 1
